### ISSUE TITLE
v1_readcurrentmactablefromdevice_body error during validation operation

### ISSUE THREAD

**Issue by schiavi-siae** [openBackhaul/MacAddressTableRecorder#111]
In MATR application, individual services /v1/read-current-mac-table-from-device, when the callback is called, the validator stop the command, the  error is the following:

"Bad Request: request.body should match exactly one schema in oneOf
    at Object.POST-/v1/read-current-mac-table-from-device-application/json ([...]\server\node_modules\express-openapi-validator\dist\middlewares\openapi.request.validator.js"

**Comment by kmohr-soprasteria** [comment]
There are multiple callbacks for that service, it is not clear to which one the error message applies.
Please provide more information.

**Comment by schiavi-siae** [comment]
In this moment i have changed  “**oneOf**” to “**anyOf**” in v1_readcurrentmactablefromdevice_body:
   [...]
 **oneOf**:

It seems correct, so I enter into the function, but I'm not sure if it's the desired behavior.
