### ISSUE TITLE
Create ServiceList for MacAddressTableRec

### ISSUE THREAD

**Issue by kurzkama** [openBackhaul/MacAddressTableRecorder#13]
First ideas what kind of services could be needed:

- provide-mac-table-of-device (Device/MAC-address/Interface/VLAN)
- provide-mac-address-at-interface/VLAN :  device + interface/VLAN => list of mac-addresses received by the device at this interface/VLAN
- provide-interface/VLAN-for-mac-address :  devices + mac address => interface/VLAN at which the mac-address is received by the device
- provide-breadcrumbs-of-mac-address :   mac-address => list of devices with list of interfaces/VLAN at which the mac-address was received by the device

**Comment by ThomasSeitz** [comment]
comment to become a reviewer

**Comment by ThomasSeitz** [comment]
Hi Markus,
I found a difference between my file and yours.
Please check together the issue:
![grafik](https://user-images.githubusercontent.com/47319210/181181955-fc058199-68f1-4fc2-9c3d-ba714e64416d.png)
