### ISSUE TITLE
MATR is getting continuously restarted after MWDI new version is deployed 

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MacAddressTableRecorder#206]
We noticed the MATR container(test_v1.0.5) is continuously restarting after upgrading the MWDI code to test_v1.1.3 in TestLab environment.

MATR container logs:
```
 callback : POST http://x.x.x.x:xxxx/v1/register-application header :{"user":"MacAddressTableRecorder","originator":"MacAddressTableRecorder","x-correlator":"188B02BE-d62E-2fC0-c90f-1342E4DBECC0","trace-indicator":"1.1","customer-journey":"1","operation-key":"n.a.","Content-Type":"application/json"}body :{"application-name":"MacAddressTableRecorder","release-number":"1.0.0","embedding-operation":"/v1/embed-yourself","client-update-operation":"/v1/update-client","operation-client-update-operation":"/v1/update-operation-client","tcp-server-list":[{"protocol":"HTTP","port":3012,"address":{"ip-address":{"ipv-4-address":"172.28.127.10"}}},{"protocol":"HTTPS","port":3012,"address":{"ip-address":{"ipv-4-address":"172.28.127.10"}}}]}response code:204
loggingErrorHandler - caught error, returning response with status code "500" and body {"code":500,"message":"response body required.","errors":[{"path":".response","message":"response body required."}]}
POST /v1/embed-yourself 500 215.287 ms - 158
/home/openbackhaul/macAddressTableRecorder/controllers/BasicServices.js:131
  await BasicServices.inquireOamRequestApprovals(body, user, xCorrelator, traceIndicator, customerJourney, req.url, NEW_RELEASE_FORWARDING_NAME)

ReferenceError: NEW_RELEASE_FORWARDING_NAME is not defined
    at SwaggerRouter.inquireOamRequestApprovals (/home/openbackhaul/macAddressTableRecorder/controllers/BasicServices.js:131:117)
    at /home/openbackhaul/macAddressTableRecorder/node_modules/oas3-tools/dist/middleware/swagger.router.js:99:40
    at Layer.handle [as handle_request] (/home/openbackhaul/macAddressTableRecorder/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/openbackhaul/macAddressTableRecorder/node_modules/express/lib/router/index.js:328:13)
    at /home/openbackhaul/macAddressTableRecorder/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/openbackhaul/macAddressTableRecorder/node_modules/express/lib/router/index.js:346:12)
    at next (/home/openbackhaul/macAddressTableRecorder/node_modules/express/lib/router/index.js:280:10)
    at /home/openbackhaul/macAddressTableRecorder/node_modules/oas3-tools/dist/middleware/swagger.parameters.js:52:13
    at Layer.handle [as handle_request] (/home/openbackhaul/macAddressTableRecorder/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/openbackhaul/macAddressTableRecorder/node_modules/express/lib/router/index.js:328:13)

```

**Comment by schiavi-siae** [comment]
Defined NEW_RELEASE_FORWARDING_NAME in BasicServces.js and fix returning error response with **status code "500". 

Test in local VM  of /v1/embed-yourself service:
Before
callback : POST http://172.28.127.11:3003/v1/record-service-request header :{"user":"User Name","originator":"MacAddressTableRecorder","x-correlator":"EEDA960E-8d8b-8B2C-e01e-6d3c517D32Bb","trace-indicator":1,"customer-journey":"unknown","operation-key":"Operation key not yet provided.","Content-Type":"application/json"}body :{"x-correlator":"550e8400-e29b-11d4-a716-446655440000","trace-indicator":"1.3.1","user":"User Name","originator":"Resolver","application-name":"MacAddressTableRecorder","release-number":"1.0.0","operation-name":"/v1/embed-yourself","response-code":200}response code:204
RequestBuilder.js:33
loggingErrorHandler - caught error, returning response with status code "500" and body {"code":500,"message":"response body required.","errors":[{"path":".response","message":"response body required."}]}


After Fix:
 callback : POST http://172.28.127.11:3003/v1/record-service-request header :{"user":"User Name","originator":"MacAddressTableRecorder","x-correlator":"De74c584-cdD1-c6eE-74fE-d8B2Dc1fbECA","trace-indicator":1,"customer-journey":"unknown","operation-key":"Operation key not yet provided.","Content-Type":"application/json"}body :{"x-correlator":"550e8400-e29b-11d4-a716-446655440000","trace-indicator":"1.3.1","user":"User Name","originator":"Resolver","application-name":"MacAddressTableRecorder","release-number":"1.0.0","operation-name":"/v1/embed-yourself","response-code":204}response code:204
