### ISSUE TITLE
Observing 500 error with API : /v1/provide-list-of-network-element-interfaces-on-path-in-generic-representation

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MacAddressTableRecorder#210]
TAG:test_v1.0.7

Observing 500 error with API : /v1/provide-list-of-network-element-interfaces-on-path-in-generic-representation

```
/v1/provide-list-of-network-element-interfaces-on-path-in-generic-representation

BODY:
{
  "input-value-list": [
    {
      "field-name": "TargetMacAddress",
      "field-value": "00:aa:aa:00:aa:18"
    }
  ]
}
```
```
curl -X POST "http://XX:XX/v1/provide-list-of-network-element-interfaces-on-path-in-generic-representation" -H "accept: application/json" -H "user: User Name" -H "originator: Resolver" -H "x-correlator: 550e8400-e29b-11d4-a716-446655440000" -H "trace-indicator: 1.3.1" -H "customer-journey: Unknown value" -H "Content-Type: application/json" -d "{\"input-value-list\":[{\"field-name\":\"TargetMacAddress\",\"field-value\":\"00:aa:aa:00:aa:18\"}]}"


http://XX:XX/v1/provide-list-of-network-element-interfaces-on-path-in-generic-representation

{
  "code": 500,
  "message": ".response['response-value-list'][0].value should be string",
  "errors": [
    {
      "path": ".response['response-value-list'][0].value",
      "message": "should be string",
      "errorCode": "type.openapi.validation"
    }
  ]
}

```

**Comment by schiavi-siae** [comment]
REQUEST:
curl -X POST "http://172.28.127.21:3011/v1/provide-list-of-network-element-interfaces-on-path-in-generic-representation" -H "accept: application/json" -H "user: User Name" -H "originator: Resolver" -H "x-correlator: 550e8400-e29b-11d4-a716-446655440000" -H "trace-indicator: 1.3.1" -H "customer-journey: Unknown value" -H "Content-Type: application/json" -d "{\"input-value-list\":[{\"field-name\":\"TargetMacAddress\",\"field-value\":\"00:aa:aa:00:aa:0c\"}]}"


RESPONSE:

Code:200
Details:
{
  "consequent-action-list": [],
  "response-value-list": [
    {
      "value": "513250004:LTP-MACINTERFACE-TTP-4-1",
      "datatype": "string",
      "field-name": "listOfNetworkElementInterfacesOnPath"
    },
    {
      "value": "513250008:LTP-MAC-TTP-PORT-A",
      "datatype": "string",
      "field-name": "listOfNetworkElementInterfacesOnPath"
    },
    {
      "value": "513250009:LTP-MAC-TTP-LAN-4",
      "datatype": "string",
      "field-name": "listOfNetworkElementInterfacesOnPath"
    },
    {
      "value": "513250010:MAC-2134647012",
      "datatype": "string",
      "field-name": "listOfNetworkElementInterfacesOnPath"
    },
    {
      "value": "513250011:MAC-2134638978",
      "datatype": "string",
      "field-name": "listOfNetworkElementInterfacesOnPath"
    }
  ]
}
