### ISSUE TITLE
Unable to retrieve all data using API:/provided-mac-table-of-all-devices

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MacAddressTableRecorder#231]
In MATR, we have more than 37000 doc counts in ELK. 
When user tried to send API:/provided-mac-table-of-all-devices, we are seeing only 148 entries in Postman/Swagger/Curl command.

**Comment by schiavi-siae** [comment]
The **PromptForProvidingAllMacTablesCausesReadingFromElasticSearch** service was returning only a subset of the results that matched the query. In Elasticsearch, when the number of documents result exceeds the default limit (which is 10 by default), the scrolling feature needs to be introduced to retrieve all results.
Scrolling allow to retrieve the results in manageable block, ensuring that you obtain all documents without losing any data. I have now added scrolling to the **PromptForProvidingAllMacTablesCausesReadingFromElasticSearch** service, so all the data present in Elasticsearch should now be available.
