### ISSUE TITLE
Timeout in profileInstancesList obsolete, handled by Controller

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MacAddressTableRecorder#47]
Can be removed:

>   - profile-name: 'IntegerProfile'
>     uuid: 'matr-1-0-0-integer-p-001'
>     capability:
>       integer-name: 'Timeout for receiving the response of the RPC'
>       unit: 'second'
>       minimum: 5
>       maximum: 2000
>     configuration:
>       integer-value: 60

(also in config-file)

The controller has a timeout configured for requests, which is 15min.

**Comment by openBackhaul** [comment]
Markus found out that RPcalls that did not succeed in 60 seconds, won't never succeed.
Doesn't make sense waiting for 15 minutes.
