### ISSUE TITLE
IntegerProfile instances should have proper integer-name values

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MacAddressTableRecorder#48]
E.g. 

>   - profile-name: 'IntegerProfile'
>     uuid: 'matr-1-0-0-integer-p-002'
>     capability:
>       integer-name: 'Maximum number of retries for executing an RPC'
>       unit:
>       minimum: 0
>       maximum: 10
>     configuration:
>       integer-value: 1

the integer-name should be moved to description and a proper name should be set in integer-name field.

Die Parametrisierung des zyklischen Prozesses sollte in MATR und MWDI gleich sein.
Name sollte wie folgt lauten:
      integer-name: 'maximumNumberOfRetries'

**Comment by openBackhaul** [comment]
**ProfileList:**
In uuid: 'matr-1-0-0-integer-p-002' the following changes shall be made:
- integer-name: 'maximumNumberOfRetries'
- unit: shall be removed
- description: 'Maximum number of retries for executing an RPC'

**CONFIGfile:**
to be changed accordingly

**Comment by kurzkama** [comment]
IntegerProfile was already updated to the new rule in current version.
