### ISSUE TITLE
Controller application name needs to be updated to new name in spec

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MacAddressTableRecorder#60]
See [documentation issue](https://github.com/openBackhaul/ApplicationPattern/issues/849).
The application name of the Controller needs to be changed from OpenDaylight to OpenDay**L**ight (with upper case L).
This needs to be done in:
- serviceList
- forwardingList
- ConfigFile

**Comment by openBackhaul** [comment]
Done. Thanks.
